services:
  dev:
    build: .
    volumes:
      - .:/app
    tty: true

  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]