#!/usr/bin/env python3
"""Build both full detection datasets (11- and 22-class) with ONE deterministic split.

Scans data/annotations/labels, pairs each label with its image in data/raw
(by stem, trying .jpg/.jpeg/.png), applies the canonical parse/skip rules,
then computes the train/val/test split ONCE (seeded shuffle from params.yaml)
and materialises two Ultralytics datasets:

  data/processed/detection11/  5-column labels, base class ids (flag stripped)
  data/processed/detection22/  5-column labels, new_cls = cls + 11 * damage_flag

Empty label files are valid negatives and enter both variants. Downstream
stages (crop_classification) must READ reports/split_manifest.json - never
re-split. Existing variant dirs are wiped on rerun (they are DVC stage outs);
data/raw and data/annotations are never touched.

Reports written: reports/split_manifest.json, reports/classes_map.json,
reports/split_skipped.json, reports/class_distribution.json.

Usage:  python scripts/prepare_split.py [--params params.yaml]
"""
from __future__ import annotations

import argparse
import logging
import random
import shutil
import sys
from collections import Counter
from pathlib import Path

import yaml

try:  # run as `python scripts/prepare_split.py` (sys.path[0] = scripts/)
    from label_common import (LINE_REASONS, SPLITS, LabelObject, index_images,
                              parse_label_file, place_image, write_json)
except ImportError:  # imported from the repository root (tests)
    from scripts.label_common import (LINE_REASONS, SPLITS, LabelObject,
                                      index_images, parse_label_file,
                                      place_image, write_json)

log = logging.getLogger("prepare_split")


def write_variant(
    out_dir: Path,
    names: list[str],
    cls_multiplier: int,
    splits: dict[str, list[str]],
    pairs: dict[str, tuple[Path, list[LabelObject]]],
) -> None:
    """Materialise one detection variant (images + 5-column labels + data.yaml)."""
    if out_dir.exists():
        shutil.rmtree(out_dir)
    for split, stems in splits.items():
        img_dir = out_dir / split / "images"
        lbl_dir = out_dir / split / "labels"
        img_dir.mkdir(parents=True, exist_ok=True)
        lbl_dir.mkdir(parents=True, exist_ok=True)
        for stem in stems:
            img, objects = pairs[stem]
            place_image(img, img_dir / img.name)
            lines = [
                f"{o.cls + cls_multiplier * o.flag} "
                f"{o.cx:.6f} {o.cy:.6f} {o.w:.6f} {o.h:.6f}"
                for o in objects
            ]
            (lbl_dir / f"{stem}.txt").write_text(
                "\n".join(lines) + ("\n" if lines else ""),
                encoding="utf-8", newline="\n")
    names_block = "\n".join(f"  {i}: {n}" for i, n in enumerate(names))
    (out_dir / "data.yaml").write_text(
        f"# generated by scripts/prepare_split.py - regenerable, machine-local\n"
        f"path: {out_dir.resolve().as_posix()}\n"
        f"train: train/images\nval: val/images\ntest: test/images\n\n"
        f"names:\n{names_block}\n",
        encoding="utf-8", newline="\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--params", type=Path, default=Path("params.yaml"))
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    params = yaml.safe_load(args.params.read_text(encoding="utf-8"))
    num_classes = int(params["classes"]["num_classes"])
    base_names = [str(params["classes"]["names"][i]) for i in range(num_classes)]
    encoded_names = base_names + [f"{n}_damaged" for n in base_names]
    split_cfg = params["split"]
    ratios = split_cfg["ratios"]
    seed = int(split_cfg["seed"])
    min_objects_warn = int(split_cfg["min_objects_warn"])

    labels_dir = Path(params["data"]["labels"])
    raw_dir = Path(params["data"]["raw_images"])
    processed_dir = Path(params["data"]["processed"])
    if not labels_dir.is_dir() or not raw_dir.is_dir():
        log.error("labels/raw dir not found - run from the repository root")
        return 2

    # -- scan & pair -------------------------------------------------------
    images_by_stem = index_images(raw_dir)
    pairs: dict[str, tuple[Path, list[LabelObject]]] = {}
    labels_without_image: list[str] = []
    bad_lines: list[dict] = []
    clamped_lines: list[dict] = []
    label_stems: set[str] = set()

    for lbl in sorted(labels_dir.glob("*.txt")):
        if lbl.name.startswith("."):  # hidden files are tool state
            continue
        label_stems.add(lbl.stem)
        img = images_by_stem.get(lbl.stem)
        if img is None:
            # orphan labels are NOT parsed: bad/clamped records here must
            # mirror what crop_classification (manifest-driven) can see
            labels_without_image.append(lbl.stem)
            continue
        objects, bad, clamped = parse_label_file(lbl, num_classes)
        bad_lines.extend(bad)
        clamped_lines.extend(clamped)
        # empty / effectively-empty label = valid negative -> still a pair
        pairs[lbl.stem] = (img, objects)

    images_without_label = sorted(
        p.name for stem, p in images_by_stem.items() if stem not in label_stems)

    if not pairs:
        log.error("no eligible (label, image) pairs - nothing to split")
        return 1

    # -- deterministic split (computed ONCE, downstream reads the manifest) -
    eligible = sorted(pairs)
    rng = random.Random(seed)
    rng.shuffle(eligible)
    n = len(eligible)
    n_test = round(n * ratios["test"])
    n_val = round(n * ratios["val"])
    splits: dict[str, list[str]] = {
        "train": eligible[n_test + n_val:],
        "val": eligible[n_test:n_test + n_val],
        "test": eligible[:n_test],
    }

    # -- write both variants -------------------------------------------------
    write_variant(processed_dir / "detection11", base_names, 0, splits, pairs)
    write_variant(processed_dir / "detection22", encoded_names, num_classes,
                  splits, pairs)

    # -- reports ------------------------------------------------------------
    reports_dir = Path("reports")
    reports_dir.mkdir(parents=True, exist_ok=True)

    write_json(reports_dir / "split_manifest.json", {
        "seed": seed,
        "ratios": {s: float(ratios[s]) for s in SPLITS},
        "counts": {s: {"images": len(splits[s]),
                       "objects": sum(len(pairs[st][1]) for st in splits[s])}
                   for s in SPLITS},
        "splits": {s: sorted(splits[s]) for s in SPLITS},
    })

    write_json(reports_dir / "classes_map.json", {
        "base_classes": {str(i): n for i, n in enumerate(base_names)},
        "encoded_classes": {str(i): n for i, n in enumerate(encoded_names)},
        "rule": f"new_cls = cls + {num_classes} * damage_flag",
        "num_base_classes": num_classes,
        "num_encoded_classes": 2 * num_classes,
    })

    reason_counts = Counter(b["reason"] for b in bad_lines)
    skipped_counts = {
        "labels_without_image": len(labels_without_image),
        "images_without_label": len(images_without_label),
        **{r: reason_counts.get(r, 0) for r in LINE_REASONS},
        "clamped": len(clamped_lines),
    }
    write_json(reports_dir / "split_skipped.json", {
        "labels_without_image": sorted(labels_without_image),
        "images_without_label": images_without_label,
        "bad_lines": bad_lines,
        "clamped_lines": clamped_lines,
        "counts": skipped_counts,
    })

    dist11 = {s: {str(i): 0 for i in range(num_classes)} for s in SPLITS}
    dist22 = {s: {str(i): 0 for i in range(2 * num_classes)} for s in SPLITS}
    for split, stems in splits.items():
        for stem in stems:
            for o in pairs[stem][1]:
                dist11[split][str(o.cls)] += 1
                dist22[split][str(o.cls + num_classes * o.flag)] += 1
    warnings = [
        f"{name} (id {i}) has only {dist22['train'][str(i)]} training objects "
        f"(< {min_objects_warn})"
        for i, name in enumerate(encoded_names)
        if dist22["train"][str(i)] < min_objects_warn
    ]
    write_json(reports_dir / "class_distribution.json", {
        "scheme11": dist11,
        "scheme22": dist22,
        "warnings": warnings,
    })

    # -- summary --------------------------------------------------------------
    for w in warnings:
        print(f"WARNING: {w}")
    log.info("eligible pairs: %d -> train=%d val=%d test=%d",
             n, len(splits["train"]), len(splits["val"]), len(splits["test"]))
    log.info("objects: train=%d val=%d test=%d",
             *(sum(len(pairs[st][1]) for st in splits[s]) for s in SPLITS))
    log.info("skipped: %s",
             ", ".join(f"{k}={v}" for k, v in skipped_counts.items()))
    log.info("class warnings: %d (see reports/class_distribution.json)",
             len(warnings))
    log.info("datasets ready: %s | %s",
             processed_dir / "detection11" / "data.yaml",
             processed_dir / "detection22" / "data.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
